update mass_transit_station set Station_THName = 'งามวงศ์วาน 2' , Station_THName_Display = 'งามวงศ์วาน 2' where Station_Code ='BR02';
update mass_transit_station set Station_THName = 'งามวงศ์วาน 18' , Station_THName_Display = 'งามวงศ์วาน 18' where Station_Code ='BR03';
update mass_transit_station set Station_THName = 'อนุสาวรีย์ชัยฯ' , Station_THName_Display = 'อนุสาวรีย์ชัยฯ' where Station_Code ='N3';
update mass_transit_station set Station_THName = 'อนุสาวรีย์ประชาธิปไตย' , Station_THName_Display = 'อนุสาวรีย์ประชาธิปไตย' where Station_Code ='OR05';
update mass_transit_station set Station_THName = 'ม.รามคำแหง' , Station_THName_Display = 'ม.รามคำแหง' where Station_Code ='OR17';
update mass_transit_station set Station_THName = 'กระทรวงสาธารณสุข' , Station_THName_Display = 'กระทรวงสาธารณสุข' where Station_Code ='PP12';
update mass_transit_station set Station_THName = 'กรุงเทพอภิวัฒน์' , Station_THName_Display = 'กรุงเทพอภิวัฒน์' where Station_Code ='A09';
update mass_transit_station set Station_THName = 'งามวงศ์วาน 48' , Station_THName_Display = 'งามวงศ์วาน 48' where Station_Code ='BR06';
update mass_transit_station set Station_THName = 'ประเสริฐมนูกิจ-ลาดปลาเค้า' , Station_THName_Display = 'ประเสริฐมนูกิจ-ลาดปลาเค้า' where Station_Code ='BR09';
update mass_transit_station set Station_THName = 'ประเสริฐมนูกิจ-เสนานิคม' , Station_THName_Display = 'ประเสริฐมนูกิจ-เสนานิคม' where Station_Code ='BR10';
update mass_transit_station set Station_THName = 'ทางต่างระดับฉลองรัช' , Station_THName_Display = 'ทางต่างระดับฉลองรัช' where Station_Code ='BR12';
update mass_transit_station set Station_THName = 'ประเสริฐมนูกิจ-นวมินทร์' , Station_THName_Display = 'ประเสริฐมนูกิจ-นวมินทร์' where Station_Code ='BR15';
update mass_transit_station set Station_THName = 'การเคหะแห่งชาติ' , Station_THName_Display = 'การเคหะแห่งชาติ' where Station_Code ='BR19';
update mass_transit_station set Station_THName = 'บางพรม' , Station_THName_Display = 'บางพรม' where Station_Code ='S14';
update mass_transit_station set Station_THName = 'วัดโพธิ์' , Station_THName_Display = 'วัดโพธิ์' where Station_Code ='S15';
update mass_transit_station set Station_THName = 'รามคำแหง 34' , Station_THName_Display = 'รามคำแหง 34' where Station_Code ='OR19';
update mass_transit_station set Station_THName = 'รามอินทรา กม.4' , Station_THName_Display = 'รามอินทรา กม.4' where Station_Code ='PK19';
update mass_transit_station set Station_THName = 'รามอินทรา กม.6' , Station_THName_Display = 'รามอินทรา กม.6' where Station_Code ='PK22';
update mass_transit_station set Station_THName = 'อนุสาวรีย์ประชาธิปไตย' , Station_THName_Display = 'อนุสาวรีย์ประชาธิปไตย' where Station_Code ='PP22';
update mass_transit_station set Station_THName = 'รพ.สมเด็จพระปิ่นเกล้า' , Station_THName_Display = 'รพ.สมเด็จพระปิ่นเกล้า' where Station_Code ='PP26';
update mass_transit_station set Station_THName = 'แยกประชาอุทิศ' , Station_THName_Display = 'แยกประชาอุทิศ' where Station_Code ='PP30';
update mass_transit_station set Station_THName = 'กรุงเทพอภิวัฒน์' , Station_THName_Display = 'กรุงเทพอภิวัฒน์' where Station_Code ='RN01';
update mass_transit_station set Station_THName = 'นางนอง' , Station_THName_Display = 'นางนอง' where Station_Code ='RS11';
update mass_transit_station set Station_THName = 'กรุงเทพอภิวัฒน์' , Station_THName_Display = 'กรุงเทพอภิวัฒน์' where Station_Code ='RW01';
update mass_transit_station set Station_THName = 'สำนักงานเขตตลิ่งชัน' , Station_THName_Display = 'สำนักงานเขตตลิ่งชัน' where Station_Code ='RWS2';
update mass_transit_station set Station_THName = 'บางขุนนนท์' , Station_THName_Display = 'บางขุนนนท์' where Station_Code ='RWS3';

update mass_transit_station_match_route set Station_THName_Display = 'งามวงศ์วาน 2'  where Station_Code ='BR02';
update mass_transit_station_match_route set Station_THName_Display = 'งามวงศ์วาน 18'  where Station_Code ='BR03';
update mass_transit_station_match_route set Station_THName_Display = 'อนุสาวรีย์ชัยฯ'  where Station_Code ='N3';
update mass_transit_station_match_route set Station_THName_Display = 'อนุสาวรีย์ประชาธิปไตย'  where Station_Code ='OR05';
update mass_transit_station_match_route set Station_THName_Display = 'ม.รามคำแหง'  where Station_Code ='OR17';
update mass_transit_station_match_route set Station_THName_Display = 'กระทรวงสาธารณสุข'  where Station_Code ='PP12';
update mass_transit_station_match_route set Station_THName_Display = 'กรุงเทพอภิวัฒน์'  where Station_Code ='A09';
update mass_transit_station_match_route set Station_THName_Display = 'งามวงศ์วาน 48'  where Station_Code ='BR06';
update mass_transit_station_match_route set Station_THName_Display = 'ประเสริฐมนูกิจ-ลาดปลาเค้า'  where Station_Code ='BR09';
update mass_transit_station_match_route set Station_THName_Display = 'ประเสริฐมนูกิจ-เสนานิคม'  where Station_Code ='BR10';
update mass_transit_station_match_route set Station_THName_Display = 'ทางต่างระดับฉลองรัช'  where Station_Code ='BR12';
update mass_transit_station_match_route set Station_THName_Display = 'ประเสริฐมนูกิจ-นวมินทร์'  where Station_Code ='BR15';
update mass_transit_station_match_route set Station_THName_Display = 'การเคหะแห่งชาติ'  where Station_Code ='BR19';
update mass_transit_station_match_route set Station_THName_Display = 'บางพรม'  where Station_Code ='S14';
update mass_transit_station_match_route set Station_THName_Display = 'วัดโพธิ์'  where Station_Code ='S15';
update mass_transit_station_match_route set Station_THName_Display = 'รามคำแหง 34'  where Station_Code ='OR19';
update mass_transit_station_match_route set Station_THName_Display = 'รามอินทรา กม.4'  where Station_Code ='PK19';
update mass_transit_station_match_route set Station_THName_Display = 'รามอินทรา กม.6'  where Station_Code ='PK22';
update mass_transit_station_match_route set Station_THName_Display = 'อนุสาวรีย์ประชาธิปไตย'  where Station_Code ='PP22';
update mass_transit_station_match_route set Station_THName_Display = 'รพ.สมเด็จพระปิ่นเกล้า'  where Station_Code ='PP26';
update mass_transit_station_match_route set Station_THName_Display = 'แยกประชาอุทิศ'  where Station_Code ='PP30';
update mass_transit_station_match_route set Station_THName_Display = 'กรุงเทพอภิวัฒน์'  where Station_Code ='RN01';
update mass_transit_station_match_route set Station_THName_Display = 'นางนอง'  where Station_Code ='RS11';
update mass_transit_station_match_route set Station_THName_Display = 'กรุงเทพอภิวัฒน์'  where Station_Code ='RW01';
update mass_transit_station_match_route set Station_THName_Display = 'สำนักงานเขตตลิ่งชัน'  where Station_Code ='RWS2';
update mass_transit_station_match_route set Station_THName_Display = 'บางขุนนนท์'  where Station_Code ='RWS3';