--
update housing set Housing_Name = replace(Housing_Name,'\r','');
update housing set Housing_ENName = replace(Housing_ENName,'\r','');

update housing set Housing_ENName = 'Baan Sinthawee
Suanthon 3' where Housing_Code = 'HP4336';
update housing set Housing_ENName = 'Baan Thanabordee
Bangbon' where Housing_Code = 'HP2231';
update housing set Housing_ENName = 'Prachasuk City' where Housing_Code = 'HP4346';
update housing set Housing_ENName = 'The Connect
Donmuang-Viphavadi' where Housing_Code = 'HP4582';
update housing set Housing_ENName = 'Pruksa Ville 82/1
Kathu-Samkong' where Housing_Code = 'HP4319';
update housing set Housing_ENName = 'Pruksa Ville 62/1
Nimitmai' where Housing_Code = 'HP3874';
update housing set Housing_ENName = 'PRUKSA VILLE 41/1
BANGKADEE-TIWANON' where Housing_Code = 'HP5557';
update housing set Housing_ENName = 'Baan Pruksa 65/1
Rangsit-Klong 2' where Housing_Code = 'HP2186';
update housing set Housing_ENName = 'Baan Pruksa 74/1
Srinakarin-Teparak' where Housing_Code = 'HP4619';
update housing set Housing_ENName = 'BAAN PRUKSA 74/1
SRINAKARIN-THEPARAK' where Housing_Code = 'HP5578';
update housing set Housing_ENName = 'Pruksa Ville 86/1
Sriracha-Bowin' where Housing_Code = 'HP3965';
update housing set Housing_ENName = 'Pruksa Ville 91/1
Salaya' where Housing_Code = 'HP3794';
update housing set Housing_ENName = 'PRUKSA VILLE 38/1
NHAMDAENG-THAPARUK' where Housing_Code = 'HP5560';
update housing set Housing_ENName = 'Pruksa Ville 71/1
Laemchabang-Banglamung' where Housing_Code = 'HP5065';
update housing set Housing_ENName = 'Baan Patcharaphorn
Suksawat 62/2' where Housing_Code = 'HP2595';
update housing set Housing_ENName = 'Baan Pruksa
Rungsit-Klong 3 64/2' where Housing_Code = 'HP4570';
update housing set Housing_ENName = 'Jirawadee
Tiwanon 45/2' where Housing_Code = 'HP4262';
update housing set Housing_ENName = 'Patreeda Avenue
Rangsit-Klong 2/2' where Housing_Code = 'HP1960';
update housing set Housing_ENName = 'Suksawat
Poon Pon' where Housing_Code = 'HP2597';
update housing set Housing_ENName = 'Pruksa Ville 59/2
Katoo-Patong' where Housing_Code = 'HP4662';
update housing set Housing_ENName = 'Baan Pruksa 38/2
Chaiyapruek-Wongwaen' where Housing_Code = 'HP3466';
update housing set Housing_ENName = 'Banpisan
Suvarnabhumi 2/2 Bang Chalong' where Housing_Code = 'HP0132';
update housing set Housing_ENName = 'Pruksa Ville 66
Bangna-Nhamdaeng' where Housing_Code = 'HP4236';
update housing set Housing_ENName = 'Baan Pruksa 49/2
Bangyai-Kaewin' where Housing_Code = 'HP4120';
update housing set Housing_ENName = 'Baan Pruksa 49/2
Bangyai-Kaewin' where Housing_Code = 'HP4124';
update housing set Housing_ENName = 'Chatluang 15/2
Pathum-Samkhok' where Housing_Code = 'HP0475';
update housing set Housing_ENName = 'Pruksa Ville 63/2
Rama 5' where Housing_Code = 'HP4191';
update housing set Housing_ENName = 'Pruksa Ville 47/2
Phutthabucha 36' where Housing_Code = 'HP4579';
update housing set Housing_ENName = 'PRUKSA VILLE 46/2
RANGSIT - KLONG 3' where Housing_Code = 'HP4901';
update housing set Housing_ENName = 'BAAN PRUKSA 65/2
RANGSIT -KLONG 2' where Housing_Code = 'HP5606';
update housing set Housing_ENName = 'PRUKSA VILLE
RANGSIT-ONGKARAK' where Housing_Code = 'HP5573';
update housing set Housing_ENName = 'PRUKSA VILLE 52/2
RATSADA-LAK KONG SI' where Housing_Code = 'HP5529';
update housing set Housing_ENName = 'PRUKSA VILLE 50/2
RAMKHAMHAENG' where Housing_Code = 'HP5535';
update housing set Housing_ENName = 'BAAN PRUKSA 86/2
LADKRABANG - SUVARNABHUMI' where Housing_Code = 'HP5930';
update housing set Housing_ENName = 'BAAN PRUKSA 58/2
LATKRABANG SUVARNABHUMI' where Housing_Code = 'HP4625';
update housing set Housing_ENName = 'Pruksa Ville 55/2
Wongwaen-Ramintra' where Housing_Code = 'HP4740';
update housing set Housing_ENName = 'Baan Pruksa
Srinakarin-Teparak' where Housing_Code = 'HP3873';
update housing set Housing_ENName = 'Baan Pruksa 87/5
Srinakarin-Bangna' where Housing_Code = 'HP3960';
update housing set Housing_ENName = 'PRUKSA VILLE 65/2
SRI SAMARN' where Housing_Code = 'HP4909';
update housing set Housing_ENName = 'PRUKSA VILLE 53/2
SAKAE NGAM-RAMA 2' where Housing_Code = 'HP5361';
update housing set Housing_ENName = 'Pruksa Ville 71/2
Laem Chabang-Banglamung' where Housing_Code = 'HP4571';
update housing set Housing_ENName = 'Baan Pruksa 38
Chaiyapruk-Wongwaen' where Housing_Code = 'HP4032';
update housing set Housing_ENName = 'Pruksa Ville 60/3
Ladkrabang' where Housing_Code = 'HP4567';
update housing set Housing_ENName = 'BAAN PRUKSA 74/3
SRINAKARIN-THEPARAK' where Housing_Code = 'HP4226';
update housing set Housing_ENName = '32 Residence
Pattanakarn 32' where Housing_Code = 'HP0468';
update housing set Housing_ENName = '33 Residence' where Housing_Code = 'HP0345';
update housing set Housing_ENName = 'Pruksa Ville 66/4
Bangna-Nham Daeng' where Housing_Code = 'HP3849';
update housing set Housing_ENName = 'Pruksa Ville 60/5
Ladkrabang' where Housing_Code = 'HP4422';
update housing set Housing_ENName = 'Grand Britania
Ratchaphruek-Rama 5' where Housing_Code = 'HP1419';
update housing set Housing_ENName = 'Casa Ville
Ramkhamhaeng - Wongwaen 2' where Housing_Code = 'HP1988';
update housing set Housing_ENName = 'Centro
Chaiyaphruek - Chaengwattana' where Housing_Code = 'HP3618';
update housing set Housing_ENName = 'CENTRO
Maha Chesadabodindranusorn Bridge 2' where Housing_Code = 'HP1933';
update housing set Housing_ENName = 'Dream Priva
Ratchaphruek-Pinklao-Kanchanaphisek' where Housing_Code = 'HP1718';
update housing set Housing_ENName = 'THE CITY
Maha Chesadabodindranusorn Bridge' where Housing_Code = 'HP2396';
update housing set Housing_ENName = 'THE MATIAS
Kalapapruek-Kanchanapisek' where Housing_Code = 'HP1783';
update housing set Housing_ENName = 'The Ricco Residence
Outerring-Chatuchot' where Housing_Code = 'HP3274';
update housing set Housing_ENName = 'Bangkok Boulevard Signature
Phetkasem-Pinklao' where Housing_Code = 'HP1574';
update housing set Housing_ENName = 'Bangkok Boulevard Signature
Ladprao-Serithai' where Housing_Code = 'HP2381';
update housing set Housing_ENName = 'Bangkok Boulevard
Donmueang-Chaengwatthana' where Housing_Code = 'HP0728';
update housing set Housing_ENName = 'Bangkok Boulevard
Ramintra-Serithai 2' where Housing_Code = 'HP2363';
update housing set Housing_ENName = 'Belgravia Exclusive Pool Villa
Bangna-Rama 9' where Housing_Code = 'HP1589';
update housing set Housing_ENName = 'Premier Resident
Sukhumvit-Poochaosamingprai' where Housing_Code = 'HP1944';
update housing set Housing_ENName = 'Maneerin Village
Laemchabang-Banglamung' where Housing_Code = 'HP2446';
update housing set Housing_ENName = 'Lalin Town Lanceo Crib
Bangna-Theparak' where Housing_Code = 'HP1931';
update housing set Housing_ENName = 'Lalin Town Lio BLISS
Theparak-Bang Bo' where Housing_Code = 'HP1745';
update housing set Housing_ENName = 'Lalin Town Lanceo Crib 2
Bangna-Suvarnabhumi' where Housing_Code = 'HP1661';
update housing set Housing_ENName = 'Lalin Town Lanceo CRIB
Phetkasem- Phutthamonthon Sai 4' where Housing_Code = 'HP2139';
update housing set Housing_ENName = 'Lanceo Crib
Theparak-Mueang Mai Bang Pli' where Housing_Code = 'HP1858';
update housing set Housing_ENName = 'Lio BLISS
Wongwaen-Pinklao' where Housing_Code = 'HP1692';
update housing set Housing_ENName = 'Supalai Ville
Wongwaen Pinklao Nakornin' where Housing_Code = 'HP4113';
update housing set Housing_ENName = 'Anabuki Thanahabitat 
Chesadabodindranusorn Bridge-Ratchapruek' where Housing_Code = 'HP1715';
update housing set Housing_ENName = 'anya
Westgate' where Housing_Code = 'HP1710';
update housing set Housing_ENName = 'Pruksa Ville 12A
Phaholyothin-Sai Mai' where Housing_Code = 'HP3591';
update housing set Housing_ENName = 'Baan Pruksa 60A
Rangsit - Bangpoon' where Housing_Code = 'HP3793';
update housing set Housing_ENName = 'Altitude Mastery' where Housing_Code = 'HP3806';
update housing set Housing_ENName = 'Baan Lumpini
Suanluang Grand Rama 9' where Housing_Code = 'HP3633';
update housing set Housing_ENName = 'Citysense
Wongwaen-Lamlukka Klong 5 By Prinsiri' where Housing_Code = 'HP0849';
update housing set Housing_ENName = 'Park Ville 3
Bung-Sriracha' where Housing_Code = 'HP2889';
update housing set Housing_ENName = 'Smile By Saksaitarn
Mabkha Rayong' where Housing_Code = 'HP3183';
update housing set Housing_ENName = 'Panna By Uchareon' where Housing_Code = 'HP4856';
update housing set Housing_ENName = 'Laddarom Elegance
Ramkhamhaeng' where Housing_Code = 'HP2688';
update housing set Housing_ENName = 'Vista Ville G
Klong 8' where Housing_Code = 'HP2593';
update housing set Housing_ENName = 'Karnkanok Town' where Housing_Code = 'HP4770';
update housing set Housing_ENName = 'KRISADANAKORN
PINKLAO - PHUTTAMONTHON' where Housing_Code = 'HP5268';
update housing set Housing_ENName = 'Lazuli
MRT Saima-Rattanathibet' where Housing_Code = 'HP3231';
update housing set Housing_ENName = 'Baan Pieamsuk Tuscany
MRT Rattanathibet' where Housing_Code = 'HP5290';
update housing set Housing_ENName = 'One Gate
Ekkamai-Ramintra' where Housing_Code = 'HP0931';
update housing set Housing_ENName = 'Patio
Ramintra' where Housing_Code = 'HP3767';
update housing set Housing_ENName = 'Silverlake Park
Suwinthawong 78' where Housing_Code = 'HP1782';
update housing set Housing_ENName = 'The Bless
Chaiyapruk-Changwattana' where Housing_Code = 'HP2841';
update housing set Housing_ENName = 'THE CONNECT
SuanLuang-Onnuch' where Housing_Code = 'HP4750';
update housing set Housing_ENName = 'THE CONNECT
Suwannaphum 2' where Housing_Code = 'HP4751';
update housing set Housing_ENName = 'The Duet
Rangsit-Klong 2' where Housing_Code = 'HP1714';
update housing set Housing_ENName = 'The Edition (Business District) 
Bangna-Wongwaen' where Housing_Code = 'HP1980';
update housing set Housing_ENName = 'The Edition
Bangna-Wongwaen' where Housing_Code = 'HP3089';
update housing set Housing_ENName = 'The Edition
Rama 9-Onnuch' where Housing_Code = 'HP3906';
update housing set Housing_ENName = 'The Edition
Rama 9-Krungthep Kreetha' where Housing_Code = 'HP2691';
update housing set Housing_ENName = 'The Edition
Suksawat-Rama 3' where Housing_Code = 'HP2011';
update housing set Housing_ENName = 'THE PLANT
CHAIYAPRUK-WONGWAEN' where Housing_Code = 'HP2605';
update housing set Housing_ENName = 'The Privatier
Ratchada 32' where Housing_Code = 'HP1101';
update housing set Housing_ENName = 'THE PROUD Townhome
304-Rojana' where Housing_Code = 'HP2568';
update housing set Housing_ENName = 'Lom Hai Jai Tranquil
Bangna' where Housing_Code = 'HP1061';
update housing set Housing_ENName = 'Urbanion
Ladprao-Sena 2' where Housing_Code = 'HP5263';
update housing set Housing_ENName = 'VELA VILLE
Onnuch-Sukhumvit  77' where Housing_Code = 'HP1295';