-- insert housing_spotlight
-- update Spotlight_Description
-- update mass_transit_line
-- insert housing_popular_carousel

-- insert housing_spotlight
INSERT INTO housing_spotlight (Spotlight_Order, Spotlight_Type, Spotlight_Code, Spotlight_Name, Spotlight_Label, Spotlight_Icon
                                , Spotlight_Inactive, Housing_Count, Housing_Count_SD, Housing_Count_DD, Housing_Count_TH
                                , Housing_Count_HO, Housing_Count_SH , Menu_List, Menu_Price_Order, Spotlight_Cover
                                , Spotlight_Title, Spotlight_Description, Keyword_TH, Keyword_ENG) 
VALUES (0, 'custom', 'CUS001', 'บ้านเดี่ยว', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านเดี่ยว | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS002', 'บ้านแฝด', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านแฝด | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS003', 'ทาวน์โฮม', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมทาวน์โฮม | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS004', 'โฮมออฟฟิศ', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโฮมออฟฟิศ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS005', 'อาคารพาณิชย์', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมอาคารพาณิชย์ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS006', 'บ้านต่ำล้าน', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านต่ำล้าน | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS007', 'โครงการ 1 - 2 ล้านบาท', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 1-2 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS008', 'โครงการ 2 - 5 ล้านบาท', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 2-5 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS009', 'โครงการ 5 - 10 ล้านบาท', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 5-10 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS010', 'โครงการ 10 - 20 ล้านบาท', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 10-20 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS011', 'โครงการ 20 - 40 ล้านบาท', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 20-40 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS012', 'โครงการ 40 - 60 ล้านบาท', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 40-60 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS013', 'โครงการ 60 - 80 ล้านบาท', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 60-80 ล้านบาท | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS014', 'โครงการ 80 ล้านบาทขึ้นไป', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ 80 ล้านบาทขึ้นไป | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS015', 'โครงการเปิดตัว 2001-2010', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2001-2010 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS016', 'โครงการเปิดตัว 2011-2020', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2011-2020 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS017', 'โครงการเปิดตัว 2021', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2021 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS018', 'โครงการเปิดตัว 2022', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2022 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS019', 'โครงการเปิดตัว 2023', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2023 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS020', 'โครงการเปิดตัว 2024', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการเปิดตัว 2024 | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS021', 'โครงการที่กำลังเปิดขาย', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการที่กำลังเปิดขาย | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS022', 'โครงการ Resale', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการ Resale | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS023', 'โครงการพร้อมอยู่', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการพร้อมอยู่ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS024', 'โครงการใหม่', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการใหม่ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS025', '16-34 ตร.ว.', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการขนาดที่ดิน 16-34 ตร.ว. | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS026', '34-50 ตร.ว.', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการขนาดที่ดิน 34-50 ตร.ว. | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS027', '50-100 ตร.ว.', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการขนาดที่ดิน 50-100 ตร.ว. | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS028', '100 ตร.ว. ขึ้นไป', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการขนาดที่ดิน 100 ตร.ว. ขึ้นไป | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS029', '2 ห้องนอน', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้าน 2 ห้องนอน | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS030', '3 ห้องนอน', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้าน 3 ห้องนอน | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS031', '4 ห้องนอน', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้าน 4 ห้องนอน | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS032', '5 ห้องนอนขึ้นไป', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้าน 5 ห้องนอนขึ้นไป | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS039', 'บ้านใกล้ ธรรมศาสตร์ รังสิต', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ธรรมศาสตร์ รังสิต | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS040', 'บ้านใกล้ ม.มหิดล ศาลายา', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.มหิดล ศาลายา | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS041', 'บ้านใกล้ ม.เกษตร บางเขนฯ', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.เกษตร บางเขนฯ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS042', 'บ้านใกล้ ม.กรุงเทพฯ', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.กรุงเทพฯ | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS043', 'บ้านใกล้ ม.หอการค้าไทย', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.หอการค้าไทย | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS044', 'บ้านใกล้ ม.รามคำแหง', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.รามคำแหง | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS045', 'บ้านใกล้ ม.ธุรกิจบัณฑิต', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ ม.ธุรกิจบัณฑิต | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS046', 'บ้านใกล้สถานี BTS', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สถานี BTS | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS047', 'บ้านใกล้สถานี MRT', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สถานี MRT | REAL DATA', '', NULL, NULL)
    , (0, 'custom', 'CUS048', 'บ้านใกล้สถานี Airport Link', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สถานี Airport Link | REAL DATA', '', NULL, NULL)
    , (1, 'spotlight', 'PS001', 'บ้านที่ดินใหญ่', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านที่ดินใหญ่ | REAL DATA', '', NULL, NULL)
    , (2, 'spotlight', 'PS002', 'บ้านพื้นที่ใช้สอยเยอะ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านพื้นที่ใช้สอยเยอะ | REAL DATA', '', NULL, NULL)
    , (3, 'spotlight', 'PS003', 'โครงการบ้านหรู', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการบ้านหรู | REAL DATA', '', NULL, NULL)
    , (4, 'spotlight', 'PS004', 'โครงการยูนิตน้อย', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมโครงการยูนิตน้อย | REAL DATA', '', NULL, NULL)
    , (5, 'spotlight', 'PS005', 'บ้านใจกลางเมือง', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใจกลางเมือง | REAL DATA', '', NULL, NULL)
    , (6, 'spotlight', 'PS006', 'บ้านใกล้ทางด่วน', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ทางด่วน | REAL DATA', '', NULL, NULL)
    , (7, 'spotlight', 'PS007', 'บ้านใกล้สถานีรถไฟฟ้า', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สถานีรถไฟฟ้า | REAL DATA', '', NULL, NULL)
    , (8, 'spotlight', 'PS008', 'บ้านใกล้สถานี Interchange', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สถานี Interchange | REAL DATA', '', NULL, NULL)
    , (9, 'spotlight', 'PS009', 'บ้านใกล้ศูนย์การค้า', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้ศูนย์การค้า | REAL DATA', '', NULL, NULL)
    , (10, 'spotlight', 'PS010', 'บ้านใกล้โรงเรียน', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้โรงเรียน | REAL DATA', '', NULL, NULL)
    , (11, 'spotlight', 'PS011', 'บ้านใกล้โรงเรียนนานาชาติ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้โรงเรียนนานาชาติ | REAL DATA', '', NULL, NULL)
    , (12, 'spotlight', 'PS012', 'บ้านใกล้มหาวิทยาลัย', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้มหาวิทยาลัย | REAL DATA', '', NULL, NULL)
    , (13, 'spotlight', 'PS013', 'บ้านใกล้สวนสาธารณะ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สวนสาธารณะ | REAL DATA', '', NULL, NULL)
    , (14, 'spotlight', 'PS014', 'บ้านใกล้สวนเบญจกิติ', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สวนเบญจกิติ | REAL DATA', '', NULL, NULL)
    , (15, 'spotlight', 'PS015', 'บ้านใกล้สวนจตุจักร', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สวนจตุจักร | REAL DATA', '', NULL, NULL)
    , (16, 'spotlight', 'PS016', 'บ้านใกล้สวนหลวงร.9', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สวนหลวงร.9 | REAL DATA', '', NULL, NULL)
    , (17, 'spotlight', 'PS017', 'บ้านใกล้สวนลุม', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สวนลุม | REAL DATA', '', NULL, NULL)
    , (18, 'spotlight', 'PS018', 'บ้านใกล้สนามบินดอนเมือง', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สนามบินดอนเมือง | REAL DATA', '', NULL, NULL)
    , (19, 'spotlight', 'PS019', 'บ้านใกล้สุวรรณภูมิ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้สุวรรณภูมิ | REAL DATA', '', NULL, NULL)
    , (20, 'spotlight', 'PS020', 'บ้านริมน้ำ', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านริมน้ำ | REAL DATA', '', NULL, NULL)
    , (21, 'spotlight', 'PS021', 'บ้านที่จอดรถเยอะ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านที่จอดรถเยอะ | REAL DATA', '', NULL, NULL)
    , (22, 'spotlight', 'PS022', 'บ้านห้องนอนเยอะ', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านห้องนอนเยอะ | REAL DATA', '', NULL, NULL)
    , (23, 'spotlight', 'PS023', 'บ้านใกล้โรงพยาบาล', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'รวมบ้านใกล้โรงพยาบาล | REAL DATA', '', NULL, NULL);

-- update Spotlight_Description
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านราคาถูก ทั้งบ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ ในราคา 1-2 ล้านบาท ทุกแบรนด์ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS007';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ ในราคา 2-5 ล้านบาท มาพร้อมข้อมูลราคาของแต่ละโซน แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS008';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการใหม่ ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ ทุกระดับราคา ทุกแบรนด์ มาพร้อมข้อมูล แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS024';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้าน ใกล้ ม.ธรรมศาสตร์ ศูนย์รังสิต ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS039';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้าน ใกล้ ม.มหิดล ศาลายา ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS040';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝด ทาวน์โฮม ใกล้สถานีรถไฟฟ้า BTS เดินทางสะดวก มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS046';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ใกล้สถานีรถไฟฟ้า MRT เดินทางสะดวก มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS047';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ใกล้สถานีรถไฟฟ้า Airport Link เดินทางสะดวก มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'CUS048';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ทุกระดับราคา ทุกแบรนด์ ที่มีพื้นที่ใช้สอยมากกว่า 400 ตร.ม. ขึ้นไป พร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS002';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านหรู Luxury ราคา 30 ล้านบาทขึ้นไป บนทำเลศักยภาพ ทั้งโครงการใหม่ และพร้อมอยู่ รวมทุกแบรนด์ พร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS003';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านยูนิตน้อย ให้ความเป็นส่วนตัว และเน้นความ Privacy ตอบโจทย์คนชอบความเงียบสงบ พร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS004';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ใจกลางเมือง โซนกรุงเทพชั้นใน (CBD-Downtown) มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS005';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านทำเลดี ใกล้ทางด่วน เดินทางสะดวก ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS006';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ทำเลดี ใกล้สถานีรถไฟฟ้า BTS, MRT และ Airport Link ทุกสถานี เดินทางสะดวก มาพร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS007';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านทำเลดี ใกล้ศูนย์การค้า ห้างสรรพสินค้า เอาใจสายช้อป ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS009';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ทุกแบรนด์ ทำเลดี ใกล้โรงเรียนนานาชาติชั้นนำ พร้อมข้อมูลราคาทั้งโครงการใหม่ พร้อมอยู่ ไปจนถึงสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS011';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ทุกแบรนด์ ทำเลดี ใกล้มหาวิทยาลัย พร้อมข้อมูลราคา ทั้งโครงการใหม่ โครงการพร้อมอยู่ ไปจนถึงสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS012';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมโครงการบ้านเดี่ยว บ้านแฝดและทาวน์โฮม ใกล้สนามบินสุวรรณภูมิ เดินทางสะดวก มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS019';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านที่มีจอดรถเยอะ เอาใจคนรักรถ ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS021';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านหลายห้องนอน (4 ห้องนอนขึ้นไป) ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS022';
update housing_spotlight set Spotlight_Description = 'REAL DATA รวมข้อมูลโครงการบ้านทำเลดี ใกล้โรงพยาบาล ทั้งบ้านเดี่ยว บ้านแฝด ทาวน์โฮม และโฮมออฟฟิศ มาพร้อมข้อมูล ราคา แผนที่ และสิ่งอำนวยความสะดวกที่อยู่ใกล้เคียง' where Spotlight_Code = 'PS023';


-- update mass_transit_line
ALTER TABLE mass_transit_line ADD MTrand_ID INT NULL AFTER Line_Name;
update mass_transit_line set MTrand_ID = 1 where Line_Code in ('LINE01','LINE02','LINE11');
update mass_transit_line set MTrand_ID = 2 where Line_Code in ('LINE04','LINE05','LINE06','LINE07','LINE10','LINE12','LINE13');
update mass_transit_line set MTrand_ID = 3 where Line_Code in ('LINE09');


-- insert housing_popular_carousel
insert into housing_popular_carousel (housing_type, popular_type, popular_Code, flipboard_display_list)
values ('Home','Custom','CUS007',1)
    , ('Home','Custom','CUS008',2)
    , ('Home','Spotlight','PS005',3)
    , ('Home','Custom','CUS024',4)
    , ('Home','Spotlight','PS003',5)
    , ('Home','Spotlight','PS006',6)
    , ('Home','Spotlight','PS007',7)
    , ('Home','Spotlight','PS013',8)
    , ('Home','Spotlight','PS009',9)
    , ('Home','Spotlight','PS011',10)
    , ('Home','Spotlight','PS002',11)
    , ('Home','Spotlight','PS021',12)
    , ('Home','Spotlight','PS022',13)
    , ('Home','Spotlight','PS004',14)
    , ('Home','Custom','CUS046',15)
    , ('Home','Custom','CUS047',16)
    , ('Home','Custom','CUS048',17)
    , ('Home','Spotlight','PS023',18)
    , ('Home','Custom','CUS039',19)
    , ('Home','Custom','CUS040',20)
    , ('Home','Spotlight','PS019',21)
    , ('SD','Custom','CUS007',1)
    , ('SD','Custom','CUS008',2)
    , ('SD','Spotlight','PS005',3)
    , ('SD','Custom','CUS024',4)
    , ('SD','Spotlight','PS003',5)
    , ('SD','Spotlight','PS006',6)
    , ('SD','Spotlight','PS007',7)
    , ('SD','Spotlight','PS013',8)
    , ('SD','Spotlight','PS009',9)
    , ('SD','Spotlight','PS011',10)
    , ('SD','Spotlight','PS002',11)
    , ('SD','Spotlight','PS021',12)
    , ('SD','Spotlight','PS022',13)
    , ('SD','Spotlight','PS004',14)
    , ('SD','Custom','CUS046',15)
    , ('SD','Custom','CUS047',16)
    , ('SD','Custom','CUS048',17)
    , ('SD','Spotlight','PS023',18)
    , ('SD','Custom','CUS039',19)
    , ('SD','Custom','CUS040',20)
    , ('SD','Spotlight','PS019',21)
    , ('DD','Custom','CUS007',1)
    , ('DD','Custom','CUS008',2)
    , ('DD','Spotlight','PS005',3)
    , ('DD','Custom','CUS024',4)
    , ('DD','Spotlight','PS003',5)
    , ('DD','Spotlight','PS006',6)
    , ('DD','Spotlight','PS007',7)
    , ('DD','Spotlight','PS013',8)
    , ('DD','Spotlight','PS009',9)
    , ('DD','Spotlight','PS011',10)
    , ('DD','Spotlight','PS002',11)
    , ('DD','Spotlight','PS021',12)
    , ('DD','Spotlight','PS022',13)
    , ('DD','Spotlight','PS004',14)
    , ('DD','Custom','CUS046',15)
    , ('DD','Custom','CUS047',16)
    , ('DD','Custom','CUS048',17)
    , ('DD','Spotlight','PS023',18)
    , ('DD','Custom','CUS039',19)
    , ('DD','Custom','CUS040',20)
    , ('DD','Spotlight','PS019',21)
    , ('TH','Custom','CUS007',1)
    , ('TH','Custom','CUS008',2)
    , ('TH','Spotlight','PS005',3)
    , ('TH','Custom','CUS024',4)
    , ('TH','Spotlight','PS003',5)
    , ('TH','Spotlight','PS006',6)
    , ('TH','Spotlight','PS007',7)
    , ('TH','Spotlight','PS013',8)
    , ('TH','Spotlight','PS009',9)
    , ('TH','Spotlight','PS011',10)
    , ('TH','Spotlight','PS002',11)
    , ('TH','Spotlight','PS021',12)
    , ('TH','Spotlight','PS022',13)
    , ('TH','Spotlight','PS004',14)
    , ('TH','Custom','CUS046',15)
    , ('TH','Custom','CUS047',16)
    , ('TH','Custom','CUS048',17)
    , ('TH','Spotlight','PS023',18)
    , ('TH','Custom','CUS039',19)
    , ('TH','Custom','CUS040',20)
    , ('TH','Spotlight','PS019',21)
    , ('HO','Custom','CUS007',1)
    , ('HO','Custom','CUS008',2)
    , ('HO','Spotlight','PS005',3)
    , ('HO','Custom','CUS024',4)
    , ('HO','Spotlight','PS003',5)
    , ('HO','Spotlight','PS006',6)
    , ('HO','Spotlight','PS007',7)
    , ('HO','Spotlight','PS013',8)
    , ('HO','Spotlight','PS009',9)
    , ('HO','Spotlight','PS011',10)
    , ('HO','Spotlight','PS002',11)
    , ('HO','Spotlight','PS021',12)
    , ('HO','Spotlight','PS022',13)
    , ('HO','Spotlight','PS004',14)
    , ('HO','Custom','CUS046',15)
    , ('HO','Custom','CUS047',16)
    , ('HO','Custom','CUS048',17)
    , ('HO','Spotlight','PS023',18)
    , ('HO','Custom','CUS039',19)
    , ('HO','Custom','CUS040',20)
    , ('HO','Spotlight','PS019',21)
    , ('SH','Custom','CUS007',1)
    , ('SH','Custom','CUS008',2)
    , ('SH','Spotlight','PS005',3)
    , ('SH','Custom','CUS024',4)
    , ('SH','Spotlight','PS003',5)
    , ('SH','Spotlight','PS006',6)
    , ('SH','Spotlight','PS007',7)
    , ('SH','Spotlight','PS013',8)
    , ('SH','Spotlight','PS009',9)
    , ('SH','Spotlight','PS011',10)
    , ('SH','Spotlight','PS002',11)
    , ('SH','Spotlight','PS021',12)
    , ('SH','Spotlight','PS022',13)
    , ('SH','Spotlight','PS004',14)
    , ('SH','Custom','CUS046',15)
    , ('SH','Custom','CUS047',16)
    , ('SH','Custom','CUS048',17)
    , ('SH','Spotlight','PS023',18)
    , ('SH','Custom','CUS039',19)
    , ('SH','Custom','CUS040',20)
    , ('SH','Spotlight','PS019',21);